server:
  port: 8848
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: tb-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GitHubBoyHaHa/tb-config.git
          username: GitHubBoyHaHa
          password: pengjun19950722
